name: Link Validator

on:
  pull_request:
  schedule:
    - cron:  '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-links:
    runs-on: Akka-Default
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.17
          apps: cs

      - name: sbt site
        run: sbt docs/makeSite

      - name: Run Link Validator
        run: cs launch net.runne::site-link-validator:0.2.5 -- .github/link-validator.conf
