name: Release

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  publish:
    name: Publish to Sonatype
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Check scalafmt rules, pull dependencies, publish BOM locally successfully
        env:
          LIGHTBEND_COMMERCIAL_MVN: ${{ secrets.LIGHTBEND_COMMERCIAL_MVN }}
        run: sbt checkPullBom

      - name: Sonatype release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        run: sbt +publishSigned
